### ISSUE TITLE
rename photos/search endpoint?

### ISSUE THREAD

**Issue by sawilde** [RHoKAustralia/witnesskingtides-api#8]
@thewheat - not sure I like the endpoint name photos/search as all it does return are counts of photos at a location, not photos - thoughts?

**Comment by thewheat** [comment]
Agreed. Something like photos/clusters perhaps?

**Comment by sawilde** [comment]
yup - sounds good

**Comment by thewheat** [comment]
Fixed in f04a826d95ac38cf14703db9d70ec73b10ccef67
